# Generated by Django 3.0 on 2019-12-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('nomor_telepon', models.CharField(max_length=11)),
                ('bidang', models.CharField(max_length=200)),
                ('jadwal_praktek', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('kandungan', models.CharField(max_length=200)),
                ('khasiat', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('nomor_telepon', models.CharField(max_length=11)),
                ('alamat', models.CharField(max_length=200)),
                ('keluhan', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=25)),
                ('kumpulan_obat', models.CharField(max_length=200)),
            ],
        ),
    ]
