# Generated by Django 3.0 on 2019-12-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hewan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
                ('berat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('umur', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Kandang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('isi_kandang', models.CharField(max_length=200)),
                ('luas_kandang', models.DecimalField(decimal_places=2, max_digits=25)),
            ],
        ),
        migrations.CreateModel(
            name='Pengunjung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('nomor_telepon', models.CharField(max_length=11)),
                ('hari_berkunjung', models.DateField(verbose_name='Hari Berkunjung')),
            ],
        ),
        migrations.CreateModel(
            name='Penjaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('nomor_telepon', models.CharField(max_length=11)),
                ('jadwal_jaga', models.CharField(max_length=200)),
            ],
        ),
    ]
